defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.finetune.train_fdpp_diffusion_agent.TrainFDPPDiffusionAgent

# FDPP Configuration for Push-T task
name: ${env_name}_fdpp_diffusion_kl${kl_weight}_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/fdpp-finetune/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: ${oc.env:DPPO_LOG_DIR}/pusht-pretrain/checkpoint/pretrained_diffusion.pt
normalization_path: ${oc.env:DPPO_DATA_DIR}/pusht/normalization.npz

seed: 42
device: cuda:0
env_name: pusht
obs_dim: 2  # Push-T uses 2D position
action_dim: 2  # 2D action space
denoising_steps: 100
ft_denoising_steps: 50  # Fewer steps for fine-tuning efficiency
cond_steps: 1
horizon_steps: 16
act_steps: 8

# FDPP specific parameters
use_preference_reward: True
kl_weight: 0.01  # Alpha parameter for KL regularization
preference_buffer_size: 10000
preference_batch_size: 256
preference_lr: 1e-4
preference_update_freq: 10
n_preference_epochs: 3
use_trajectory_reward: False  # Use state-level rewards for Push-T
preference_hidden_dims: [256, 256]
preference_activation: relu
preference_output_activation: tanh
use_action_in_reward: False

env:
  n_envs: 50
  name: ${env_name}
  max_episode_steps: 200
  reset_at_iteration: True
  save_video: True
  best_reward_threshold_for_success: 0.9
  save_full_observations: True
  wrappers:
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      pass_full_observations: ${env.save_full_observations}
      reset_within_step: False

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: fdpp-${env_name}-finetune
  run: ${now:%H-%M-%S}_${name}

train:
  n_train_itr: 100
  n_critic_warmup_itr: 2
  n_steps: ${eval:'round(${env.max_episode_steps} / ${act_steps})'}
  gamma: 0.99
  actor_lr: 1e-5
  actor_weight_decay: 0
  actor_lr_scheduler:
    first_cycle_steps: 100
    warmup_steps: 10
    min_lr: 1e-6
  critic_lr: 1e-3
  critic_weight_decay: 0
  critic_lr_scheduler:
    first_cycle_steps: 100
    warmup_steps: 10
    min_lr: 1e-4
  save_model_freq: 10
  val_freq: 10
  force_train: False
  render:
    freq: 5
    num: 5
  # PPO specific
  reward_scale_running: True
  reward_scale_const: 1.0
  gae_lambda: 0.95
  batch_size: ${eval:'round(${train.n_steps} * ${env.n_envs} * ${ft_denoising_steps} / 2)'}
  update_epochs: 10
  vf_coef: 0.5
  target_kl: 0.01
  clip_ratio: 0.2

model:
  _target_: model.diffusion.diffusion_ppo.PPODiffusion
  # Diffusion specific parameters
  gamma_denoising: 0.95
  clip_ploss_coef: 0.1
  clip_ploss_coef_base: 0.1
  clip_ploss_coef_rate: 1
  randn_clip_value: 3
  min_sampling_denoising_std: 0.1
  min_logprob_denoising_std: 0.1
  learn_eta: False
  # Network architecture
  network_path: ${base_policy_path}
  actor:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    time_dim: 16
    mlp_dims: [256, 256, 256]
    activation_type: ReLU
    residual_style: True
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
  critic:
    _target_: model.common.critic.CriticObs
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    mlp_dims: [256, 256, 256]
    activation_type: Mish
    residual_style: True
  ft_denoising_steps: ${ft_denoising_steps}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  device: ${device}