defaults:
  - _self_
hydra:
  run:  
    dir: ${logdir}
_target_: agent.finetune.train_sac_diffusion_ebm_agent.TrainSACDiffusionEBMAgent

name: ${env_name}_sac_diffusion_ebm_mlp_ta${horizon_steps}_td${denoising_steps}_tdf${ft_denoising_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/gym-finetune/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: ${oc.env:DPPO_LOG_DIR}/gym-pretrain/halfcheetah-medium-v2_pre_diffusion_mlp_ta4_td20/2024-06-12_23-04-42/checkpoint/state_3000.pt
normalization_path: ${oc.env:DPPO_DATA_DIR}/gym/${env_name}/normalization.npz

seed: 42
device: cuda:0
env_name: halfcheetah-medium-v2
obs_dim: 17
action_dim: 6
denoising_steps: 20
ft_denoising_steps: 10
cond_steps: 1
horizon_steps: 4
act_steps: 4

env:
  n_envs: 40
  name: ${env_name}
  max_episode_steps: 1000
  reset_at_iteration: False
  save_video: False
  best_reward_threshold_for_success: 3  # success rate not relevant for gym tasks
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: ${normalization_path}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: gym-${env_name}-finetune
  run: ${now:%H-%M-%S}_${name}

train:
  n_train_itr: 1000
  n_explore_steps: 1000
  n_steps: 500
  gamma: 0.99
  tau: 0.005  # Target network update rate
  alpha: 0.2  # Entropy regularization coefficient
  auto_alpha: True  # Automatically tune alpha
  target_entropy: -6  # Target entropy for auto alpha
  actor_lr: 3e-4
  critic_lr: 3e-4
  value_lr: 3e-4
  save_model_freq: 100
  val_freq: 10
  render:
    freq: 1
    num: 0
  # SAC specific
  buffer_size: 1000000
  batch_size: 256
  update_freq: 1
  gradient_steps: 1

model:
  _target_: model.diffusion.diffusion_sac_ebm.SACDiffusionEBM
  # HP to tune
  gamma_denoising: 0.99
  randn_clip_value: 3
  min_sampling_denoising_std: 0.1
  min_logprob_denoising_std: 0.1
  # EBM specific parameters
  use_ebm_reward_shaping: True
  pbrs_lambda: 0.5
  pbrs_beta: 1.0
  pbrs_alpha: 0.1
  pbrs_M: 4
  pbrs_use_mu_only: True
  pbrs_k_use_mode: "tail:6"
  #
  network_path: ${base_policy_path}
  actor:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    time_dim: 16
    mlp_dims: [512, 512, 512]
    activation_type: ReLU
    residual_style: True
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
  critic_q1:
    _target_: model.common.critic.CriticObsAct
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    mlp_dims: [256, 256, 256]
    activation_type: Mish
    residual_style: True
    action_dim: ${action_dim}
    action_steps: ${act_steps}
    double_q: False
  critic_q2:
    _target_: model.common.critic.CriticObsAct
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    mlp_dims: [256, 256, 256]
    activation_type: Mish
    residual_style: True
    action_dim: ${action_dim}
    action_steps: ${act_steps}
    double_q: False
  critic_v:
    _target_: model.common.critic.CriticObs
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    mlp_dims: [256, 256, 256]
    activation_type: Mish
    residual_style: True
  ebm_model:
    _target_: model.ebm.ebm.EBMWrapper
    # EBM model configuration
    hidden_dim: 256
    num_layers: 3
    activation: "relu"
  ft_denoising_steps: ${ft_denoising_steps}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  device: ${device}
