defaults:
  - _self_

hydra:
  run:
    dir: ${logdir}

_target_: agent.finetune.train_simple_mlp_ppo_agent.TrainSimpleMLP_PPOAgent

name: ${env_name}_simple_mlp_ppo_ebm_ta${horizon_steps}
logdir: ${oc.env:DPPO_LOG_DIR,${hydra:runtime.cwd}/log}/gym-finetune/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}

seed: 42
device: cuda:0
env_name: hopper-medium-v2
obs_dim: 11
action_dim: 3
cond_steps: 1
horizon_steps: 4
act_steps: 4

env:
  n_envs: 40  # 增加环境数，更多样化的经验
  name: ${env_name}
  max_episode_steps: 500
  reset_at_iteration: False
  save_video: False
  best_reward_threshold_for_success: 3600
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: ${oc.env:DPPO_DATA_DIR,${hydra:runtime.cwd}/data}/gym/${env_name}/normalization.npz
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

# wandb: null
wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: gym-${env_name}-finetune-simple-ppo
  run: ${name}_SimpleMLP_PPO_EBM
  group: ${oc.env:WANDB_GROUP,${env_name}-simple-ppo-baseline}
  tags: [SimpleMLP, PPO, EBM_Reward, Temperature_Smooth]

train:
  n_train_itr: 100
  n_critic_warmup_itr: 0
  n_steps: 500
  gamma: 0.99

  actor_lr: 3e-4
  actor_weight_decay: 1e-4
  actor_lr_scheduler:
    first_cycle_steps: 1000
    warmup_steps: 10
    min_lr: 5e-6

  critic_lr: 1e-3
  critic_weight_decay: 0
  critic_lr_scheduler:
    first_cycle_steps: 1000
    warmup_steps: 10
    min_lr: 1e-3

  save_model_freq: 50
  val_freq: 10
  log_freq: 1
  render:
    freq: 50
    num: 0

  reward_scale_running: False
  reward_scale_const: 1.0
  gae_lambda: 0.95

  # 数据与优化
  batch_size: 20000          # 每次更新使用的总样本数（如 40 env × 500 steps）
  minibatch_size: 64         # 每次迭代的小批量
  update_epochs: 10          # SB3/经典设置一般 10

  # PPO 关键超参（新增/调整）
  clip_range: 0.2
  clip_range_vf: 0.2
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  normalize_adv: True
  target_kl: 0.02

model:
  _target_: model.rl.simple_mlp_ppo.SimpleMLP_PPO
  
  # PPO parameters
  clip_ploss_coef: 0.2
  clip_vloss_coef: 0.2
  norm_adv: True
  
  # Reward configuration
  use_ebm_reward: True
  ebm_reward_scale: 1.0
  ebm_reward_clip_max: 100
  use_auto_scaling: False
  
  # Dynamic normalization with stronger signal
  use_dynamic_normalization: True
  normalization_momentum: 0.99  # Faster adaptation (was 0.99)
  temperature_scale: 1.0  # Much lower for stronger differences (was 1.0)
  normalization_epsilon: 1e-8  # Numerical stability constant
  
  # EBM configuration
  ebm:
    embed_dim: 256
    nhead: 8
    depth: 4
    dropout: 0.0
    use_cls_token: False
    num_views: null
  
  # EBM checkpoint path
  ebm_ckpt_path: /scr/zhaoyang/outputs/gym_one_action_t_idx/Hopper-v2-no-gp/ebm_best_val_hopper-v2-medium.pt
  
  # Network configuration
  actor:
    _target_: model.common.mlp_gaussian.Gaussian_MLP
    action_dim: ${action_dim}
    horizon_steps: ${horizon_steps}
    cond_dim: 11  # ${obs_dim} * ${cond_steps} = 11 * 1
    mlp_dims: [256, 256, 256]
    activation_type: ReLU
    tanh_output: True
    residual_style: False
    use_layernorm: False
    dropout: 0.1
    fixed_std: null
    learn_fixed_std: False
    std_min: 0.05
    std_max: 1.0
    
  critic:
    _target_: model.common.critic.CriticObs
    cond_dim: 11  # ${obs_dim} * ${cond_steps} = 11 * 1
    mlp_dims: [256, 256, 256]
    activation_type: ReLU
    residual_style: False

  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  device: ${device}