defaults:
  - _self_

hydra:
  run:
    dir: ${logdir}

_target_: agent.finetune.train_simple_mlp_ppo_agent.TrainSimpleMLP_PPOAgent

name: ${env_name}_simple_mlp_ppo_env_explore_ta${horizon_steps}
logdir: ${oc.env:DPPO_LOG_DIR,${hydra:runtime.cwd}/log}/gym-finetune/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}

seed: 42
device: cuda:0
env_name: hopper-medium-v2
obs_dim: 11
action_dim: 3
cond_steps: 1
horizon_steps: 4
act_steps: 4

env:
  n_envs: 60  # 增加环境数，更多样化的经验
  name: ${env_name}
  max_episode_steps: 1000
  reset_at_iteration: False
  save_video: False
  best_reward_threshold_for_success: 3600
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: ${oc.env:DPPO_DATA_DIR,${hydra:runtime.cwd}/data}/gym/${env_name}/normalization.npz
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: gym-${env_name}-finetune-simple-ppo-explore
  run: ${name}_SimpleMLP_PPO_Env_Explore
  group: ${oc.env:WANDB_GROUP,${env_name}-simple-ppo-explore}
  tags: [SimpleMLP, PPO, Env_Reward, High_Exploration]

train:
  n_train_itr: 300
  n_critic_warmup_itr: 0
  n_steps: 800  # 适中的轨迹长度
  gamma: 0.99
  
  # 探索友好的学习率
  actor_lr: 1e-3  # 更高的学习率促进探索
  actor_weight_decay: 1e-5  # 轻微正则化
  actor_lr_scheduler:
    first_cycle_steps: 1500
    warmup_steps: 100  # 更长预热期
    min_lr: 1e-5
  
  critic_lr: 3e-3
  critic_weight_decay: 1e-5
  critic_lr_scheduler:
    first_cycle_steps: 1500
    warmup_steps: 100
    min_lr: 1e-5
  
  save_model_freq: 50
  val_freq: 20  # 降低评估频率，更专注训练
  log_freq: 2
  render:
    freq: 100
    num: 0
  
  # 促进探索的PPO设置
  reward_scale_running: False  # 关闭奖励标准化，保持原始奖励信号
  reward_scale_const: 0.1  # 降低奖励缩放，增加探索
  gae_lambda: 0.95
  batch_size: 30000  # 更大批量
  update_epochs: 4  # 减少更新次数，避免过拟合
  vf_coef: 0.25  # 降低价值函数权重
  target_kl: 0.1  # 放宽KL限制，允许更激进探索

model:
  _target_: model.rl.simple_mlp_ppo.SimpleMLP_PPO
  
  # 探索友好的PPO参数
  clip_ploss_coef: 0.4  # 更大的剪切系数
  clip_vloss_coef: 0.4
  norm_adv: False  # 关闭优势标准化，保持探索动力
  
  # Reward configuration
  use_ebm_reward: False
  ebm_reward_scale: 1.0
  ebm_reward_clip_max: 60.0
  use_auto_scaling: False
  
  # EBM configuration (not used)
  ebm:
    embed_dim: 256
    nhead: 8
    depth: 4
    dropout: 0.0
    use_cls_token: False
    num_views: null
  
  # 网络架构 - 平衡表达能力和探索
  actor:
    _target_: model.common.mlp_gaussian.Gaussian_MLP
    action_dim: ${action_dim}
    horizon_steps: ${horizon_steps}
    cond_dim: 11
    mlp_dims: [256, 256, 256]
    activation_type: ReLU
    tanh_output: True
    residual_style: False
    use_layernorm: False
    dropout: 0.2  # 更高dropout促进探索
    fixed_std: null
    learn_fixed_std: False
    std_min: 0.1   # 更高最小标准差
    std_max: 2.0   # 更高最大标准差
    
  critic:
    _target_: model.common.critic.CriticObs
    cond_dim: 11
    mlp_dims: [256, 256, 256]
    activation_type: ReLU
    residual_style: False

  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  device: ${device}