defaults:
  - _self_

hydra:
  run:
    dir: ${logdir}

_target_: agent.finetune.train_simple_mlp_ppo_agent.TrainSimpleMLP_PPOAgent

name: ${env_name}_simple_mlp_ppo_ebm_fixed_ta${horizon_steps}
logdir: ${oc.env:DPPO_LOG_DIR,${hydra:runtime.cwd}/log}/gym-finetune/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}

seed: 42
device: cuda:0
env_name: hopper-medium-v2
obs_dim: 11
action_dim: 3
cond_steps: 1
horizon_steps: 4
act_steps: 4

env:
  n_envs: 40
  name: ${env_name}
  max_episode_steps: 1000
  reset_at_iteration: False
  save_video: False
  best_reward_threshold_for_success: 3600
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: ${oc.env:DPPO_DATA_DIR,${hydra:runtime.cwd}/data}/gym/${env_name}/normalization.npz
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: gym-${env_name}-finetune-simple-ppo
  run: ${name}_SimpleMLP_PPO_EBM_Fixed
  group: ${oc.env:WANDB_GROUP,${env_name}-simple-ppo-baseline}
  tags: [SimpleMLP, PPO, EBM_Mixed, Fixed]

train:
  n_train_itr: 300
  n_critic_warmup_itr: 0
  n_steps: 800
  gamma: 0.99
  
  # More conservative learning rates
  actor_lr: 3e-4  # Reduced from 1e-3
  actor_weight_decay: 1e-5
  actor_lr_scheduler:
    first_cycle_steps: 1500
    warmup_steps: 100
    min_lr: 1e-5
  
  critic_lr: 1e-3  # Reduced from 3e-3
  critic_weight_decay: 1e-5
  critic_lr_scheduler:
    first_cycle_steps: 1500
    warmup_steps: 100
    min_lr: 1e-5
  
  save_model_freq: 50
  val_freq: 20
  log_freq: 2
  render:
    freq: 100
    num: 0
  
  # Fixed PPO settings for stability
  reward_scale_running: True  # Enable running normalization
  reward_scale_const: 1.0  # Increased from 0.1
  gae_lambda: 0.95
  batch_size: 30000
  update_epochs: 4
  vf_coef: 0.5  # Increased from 0.25
  target_kl: 0.05  # Tightened from 0.1

model:
  _target_: model.rl.simple_mlp_ppo.SimpleMLP_PPO
  
  # More conservative PPO parameters
  clip_ploss_coef: 0.2  # Reduced from 0.4
  clip_vloss_coef: 0.2  # Reduced from 0.4
  norm_adv: True  # Enable advantage normalization
  
  # CRITICAL FIX: Disable EBM or use mixed rewards
  use_ebm_reward: False  # DISABLED due to negative correlation
  # Alternative: if you must use EBM, consider:
  # use_ebm_reward: True
  # ebm_reward_weight: 0.1  # Only 10% EBM, 90% environment
  
  ebm_reward_scale: 10.0  # Increased from 1.0 to amplify signal
  ebm_reward_clip_max: 10.0
  use_auto_scaling: False
  
  # Adjusted normalization for stronger signal
  use_dynamic_normalization: True
  normalization_momentum: 0.95  # Faster adaptation (was 0.99)
  temperature_scale: 0.5  # Much lower for stronger differences (was 2.0)
  normalization_epsilon: 1e-8
  
  # EBM configuration
  ebm:
    embed_dim: 256
    nhead: 8
    depth: 4
    dropout: 0.0
    use_cls_token: False
    num_views: null
  
  # EBM checkpoint path
  ebm_ckpt_path: /scr/zhaoyang/outputs/gym_one_action_t_idx/Hopper-v2-no-gp/ebm_best_val_hopper-v2-medium.pt
  
  # Network configuration
  actor:
    _target_: model.common.mlp_gaussian.Gaussian_MLP
    action_dim: ${action_dim}
    horizon_steps: ${horizon_steps}
    cond_dim: 11
    mlp_dims: [256, 256, 256]
    activation_type: ReLU
    tanh_output: True
    residual_style: False
    use_layernorm: False
    dropout: 0.1  # Reduced from 0.2
    fixed_std: null
    learn_fixed_std: False
    std_min: 0.05  # Tightened from 0.1
    std_max: 1.0   # Reduced from 2.0
    
  critic:
    _target_: model.common.critic.CriticObs
    cond_dim: 11
    mlp_dims: [256, 256, 256]
    activation_type: ReLU
    residual_style: False

  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  device: ${device}